version: '3'
services:
    web:
        build:
            context: ./
            dockerfile: docker/web.docker
        volumes:
            - ./Sample_Restful_API:/var/www
        ports:
            - "80:80"
        links:
            - app
    app:
        image: sanchaiwp/api_app:latest
        volumes:
            - ./Sample_Restful_API:/var/www